CREATE DATABASE Kitabxana

USE Kitabxana

CREATE TABLE AUTHORS (
    ID INT PRIMARY KEY IDENTITY,
    NAME NVARCHAR(100) NOT NULL,
    SURNAME NVARCHAR(100) NOT NULL
)

CREATE TABLE BOOKS (
    ID INT PRIMARY KEY IDENTITY,
    NAME NVARCHAR(100) CHECK(LEN(NAME)>=2),
    AUTHORID INT FOREIGN KEY REFERENCES AUTHORS(ID),
    PAGECOUNT INT CHECK(PAGECOUNT>=10),
)

INSERT INTO AUTHORS(NAME,SURNAME)
VALUES
(N'ELMAR',N'QARAYEV'),
(N'KENAN',N'TAGIYEV'),
(N'ILHAM',N'IBRAHIMOV'),
(N'CINGIZ',N'ESGEREV'),
(N'CAVID',N'QULIYEV')

INSERT INTO BOOKS(NAME,AUTHORID,PAGECOUNT)
VALUES
(N'YAD',2,561),
(N'SEFILLER',4,65),
(N'SEKER PORTAGALI',3,123),
(N'QURUR VE QEREZ',2,456),
(N'Kitab 1',2,356),
(N'Kitab 2',4,300),
(N'Kitab 3',2,240),
(N'YUZ ILIN TENHALIGI',5,34)

SELECT B.ID,B.NAME,B.PAGECOUNT,CONCAT(A.NAME,' ',A.SURNAME) AS AuthorFullname FROM Books AS B
JOIN Authors AS A ON A.ID=B.AUTHORID

CREATE VIEW VW_BooksWithAuthor
AS
SELECT B.ID,B.NAME,B.PAGECOUNT,CONCAT(A.NAME,' ',A.SURNAME) AS AuthorFullname FROM Books AS B
JOIN Authors AS A ON A.ID=B.AUTHORID


CREATE PROCEDURE USP_SearchBooks 
@SEARCH NVARCHAR(20)
AS
SELECT * FROM VW_BooksWithAuthor AS B
WHERE B.Name LIKE CONCAT('%',@SEARCH,'%') OR B.AuthorFullname LIKE CONCAT('%',@SEARCH,'%') 


EXEC USP_SearchBooks 'Q'

CREATE PROCEDURE USP_UPDATE_BOOK
@Id INT,@PAGE INT
AS
UPDATE Books SET PAGECOUNT=@PAGE WHERE Id=@Id

SELECT * FROM BOOKS

EXEC USP_UPDATE_BOOK 3,101

SELECT 
T.ID,
T.FULLNAME,
T.BOOKS_COUNT,
CASE WHEN T.PAGECOUNT IS NULL
THEN 0
ELSE T.PAGECOUNT 
END AS PAGECOUNT
FROM (SELECT
A.ID,
CONCAT(A.NAME,' ',A.SURNAME) AS FULLNAME,
(SELECT COUNT(*) FROM Books WHERE BOOKS.AUTHORID=A.ID) AS BOOKS_COUNT,
(SELECT MAX(BOOKS.PAGECOUNT) FROM Books WHERE BOOKS.AUTHORID=A.ID) AS PAGECOUNT
FROM AUTHORS AS A) AS T


SELECT
A.ID,
CONCAT(A.NAME,' ',A.SURNAME) AS FULLNAME,
(SELECT COUNT(*) FROM Books WHERE BOOKS.AUTHORID=A.ID) AS BOOKS_COUNT,
(SELECT COALESCE(MAX(BOOKS.PAGECOUNT),0) FROM Books WHERE BOOKS.AUTHORID=A.ID) AS PAGECOUNT
FROM AUTHORS AS A




